// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Daniel",
            "url": "https://github.com/Leinadium/puc-disciplinas"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/avaliacoes": {
            "get": {
                "description": "Coleta todas as avaliacoes",
                "produces": [
                    "application/json"
                ],
                "summary": "Coleta todas as avaliacoes",
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/avaliacoes.ResultGetAvaliacao"
                        }
                    },
                    "401": {
                        "description": "Nao logado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao executar query das disciplinas",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/avaliacoes/disciplina": {
            "post": {
                "description": "Salva uma avaliacao de disciplina",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Salva uma avaliacao de disciplina",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/avaliacoes.InputDisciplinaPost"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Avaliacao salva com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Requisicao invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Nao logado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Nao foi possivel salvar sua avaliacao",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta uma avaliacao de disciplina",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Deleta uma avaliacao de disciplina",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/avaliacoes.InputDisciplinaDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Avaliacao deletada com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Requisicao invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Nao logado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Nao foi possivel deletar sua avaliacao",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/avaliacoes/professor": {
            "post": {
                "description": "Salva uma avaliacao de professor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Salva uma avaliacao de professor",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/avaliacoes.InputProfessorPost"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Avaliacao salva com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Requisicao invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Nao logado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Nao foi possivel salvar sua avaliacao",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta uma avaliacao de professor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Deleta uma avaliacao de professor",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/avaliacoes.InputProfessorDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Avaliacao deletada com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Requisicao invalida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Nao logado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Nao foi possivel deletar sua avaliacao",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/disciplina/info": {
            "get": {
                "description": "Coleta a informação completa de uma disciplina",
                "produces": [
                    "application/json"
                ],
                "summary": "Coleta a informação completa de uma disciplina",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Codigo da disciplina",
                        "name": "c",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/disciplinas.ResultInfo"
                            }
                        }
                    },
                    "404": {
                        "description": "Disciplina nao encontrada",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao executar query",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/grade": {
            "get": {
                "description": "Coleta uma grade",
                "produces": [
                    "application/json"
                ],
                "summary": "Coleta uma grade",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da grade",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "ID nao fornecido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Grade nao encontrada",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao conectar ao banco de dados",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Salva uma grade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Salva uma grade",
                "parameters": [
                    {
                        "description": "Grade a ser salva",
                        "name": "grade",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Erro no corpo da requisicao",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Nao logado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao salvar grade",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/historico": {
            "post": {
                "description": "Envia um histórico",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Envia um histórico",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Arquivo do histórico",
                        "name": "historico",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResultHistorico"
                        }
                    },
                    "400": {
                        "description": "Erro ao ler arquivo (3)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Nao logado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao enviar histórico para o microserviço",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "get": {
                "description": "Testa o login do usuário através do cookie.",
                "produces": [
                    "application/json"
                ],
                "summary": "Verifica o login do usuário",
                "responses": {
                    "200": {
                        "description": "Sucesso",
                        "schema": {
                            "$ref": "#/definitions/controllers.ResultCheck"
                        }
                    },
                    "401": {
                        "description": "Não logado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Faz login do usuário, setando o cookie",
                "produces": [
                    "application/json"
                ],
                "summary": "Faz login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Usuário",
                        "name": "usuario",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Senha",
                        "name": "senha",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Nome do usuário",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Usuário ou senha não informados",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Usuário ou senha incorretos",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao acessar o serviço de login",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Faz logout do usuario, resetando o cookie",
                "produces": [
                    "application/json"
                ],
                "summary": "Faz logout do usuario",
                "responses": {
                    "200": {
                        "description": "Logout realizado com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao salvar sessão",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pesquisa/cursadas": {
            "get": {
                "description": "Coleta os codigos das disciplinas que o usuario cursou",
                "produces": [
                    "application/json"
                ],
                "summary": "Coleta os codigos das disciplinas que o usuario cursou",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/disciplinas.ResultCodigo"
                            }
                        }
                    },
                    "401": {
                        "description": "Usuario nao logado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao executar query",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pesquisa/faltacursar": {
            "get": {
                "description": "Coleta o código das disciplinas que o usuário falta cursar. É vazio se o usuário nao estiver logado.",
                "produces": [
                    "application/json"
                ],
                "summary": "Coleta as disciplinas que o usuario falta cursar",
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/disciplinas.ResultCodigo"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao executar query",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pesquisa/info": {
            "get": {
                "description": "Coleta as informações das disciplinas, além da data de modificação.",
                "produces": [
                    "application/json"
                ],
                "summary": "Coleta todas as disciplinas",
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/disciplinas.ResultCompleto"
                        }
                    },
                    "500": {
                        "description": "Erro ao executar query",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pesquisa/podecursar": {
            "get": {
                "description": "Coleta o código das disciplinas que o usuário pode cursar",
                "produces": [
                    "application/json"
                ],
                "summary": "Coleta as disciplinas que o usuario pode cursar",
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/disciplinas.ResultCodigo"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao executar query",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/recomendacao": {
            "post": {
                "description": "Coleta as disciplinas recomendadas",
                "produces": [
                    "application/json"
                ],
                "summary": "Coleta as disciplinas recomendadas",
                "parameters": [
                    {
                        "description": "Corpo da requisicao",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recomendacao.InputRecomendacao"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/recomendacao.ResultAlg"
                            }
                        }
                    },
                    "400": {
                        "description": "Erro ao ler corpo da requisicao",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao executar query",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "avaliacoes.InputDisciplinaDelete": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                }
            }
        },
        "avaliacoes.InputDisciplinaPost": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "nota": {
                    "type": "integer"
                }
            }
        },
        "avaliacoes.InputProfessorDelete": {
            "type": "object",
            "properties": {
                "nome": {
                    "type": "string"
                }
            }
        },
        "avaliacoes.InputProfessorPost": {
            "type": "object",
            "properties": {
                "nome": {
                    "type": "string"
                },
                "nota": {
                    "type": "integer"
                }
            }
        },
        "avaliacoes.ItemDisciplinaCompleta": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "media": {
                    "$ref": "#/definitions/null.Float"
                },
                "nome": {
                    "type": "string"
                },
                "nota": {
                    "$ref": "#/definitions/null.Int"
                },
                "qtd": {
                    "type": "integer"
                }
            }
        },
        "avaliacoes.ItemProfessorCompleto": {
            "type": "object",
            "properties": {
                "media": {
                    "$ref": "#/definitions/null.Float"
                },
                "nome": {
                    "type": "string"
                },
                "nota": {
                    "$ref": "#/definitions/null.Int"
                },
                "qtd": {
                    "type": "integer"
                }
            }
        },
        "avaliacoes.ResultGetAvaliacao": {
            "type": "object",
            "properties": {
                "disciplinas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/avaliacoes.ItemDisciplinaCompleta"
                    }
                },
                "professores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/avaliacoes.ItemProfessorCompleto"
                    }
                }
            }
        },
        "controllers.ResultCheck": {
            "type": "object",
            "properties": {
                "curriculo": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "usuario": {
                    "type": "string"
                }
            }
        },
        "controllers.ResultHistorico": {
            "type": "object",
            "properties": {
                "curriculo": {
                    "type": "string"
                },
                "inseridos": {
                    "type": "integer"
                }
            }
        },
        "disciplinas.ResultCodigo": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                }
            }
        },
        "disciplinas.ResultCompleto": {
            "type": "object",
            "properties": {
                "disciplinas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/disciplinas.ResultLista"
                    }
                },
                "modificacao": {
                    "$ref": "#/definitions/models.Modificacao"
                }
            }
        },
        "disciplinas.ResultInfo": {
            "type": "object",
            "properties": {
                "codDiscDepen": {
                    "type": "string"
                },
                "codigo": {
                    "type": "string"
                },
                "creditos": {
                    "type": "integer"
                },
                "ementa": {
                    "type": "string"
                },
                "grupoPrereq": {
                    "type": "integer"
                },
                "mediaAvaliacao": {
                    "type": "number"
                },
                "mediaGrau": {
                    "type": "number"
                },
                "nome": {
                    "type": "string"
                },
                "qtdAlunos": {
                    "type": "integer"
                },
                "qtdAvaliacoes": {
                    "type": "integer"
                }
            }
        },
        "disciplinas.ResultLista": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "creditos": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "qtdTurmas": {
                    "type": "integer"
                },
                "qtdVagas": {
                    "type": "integer"
                }
            }
        },
        "models.Modificacao": {
            "type": "object",
            "properties": {
                "dataEmenta": {
                    "type": "string"
                },
                "dataGeral": {
                    "type": "string"
                }
            }
        },
        "null.Float": {
            "type": "object",
            "properties": {
                "float64": {
                    "type": "number"
                },
                "valid": {
                    "description": "Valid is true if Float64 is not NULL",
                    "type": "boolean"
                }
            }
        },
        "null.Int": {
            "type": "object",
            "properties": {
                "int64": {
                    "type": "integer"
                },
                "valid": {
                    "description": "Valid is true if Int64 is not NULL",
                    "type": "boolean"
                }
            }
        },
        "recomendacao.InputEscolha": {
            "type": "object",
            "properties": {
                "disciplina": {
                    "type": "string"
                },
                "turma": {
                    "type": "string"
                }
            }
        },
        "recomendacao.InputRecomendacao": {
            "type": "object",
            "properties": {
                "escolhas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recomendacao.InputEscolha"
                    }
                }
            }
        },
        "recomendacao.ResultAlg": {
            "type": "object",
            "properties": {
                "cod": {
                    "type": "string"
                },
                "pes": {
                    "$ref": "#/definitions/recomendacao.ResultPesos"
                },
                "val": {
                    "type": "number"
                }
            }
        },
        "recomendacao.ResultPesos": {
            "type": "object",
            "properties": {
                "a": {
                    "type": "number"
                },
                "c": {
                    "type": "number"
                },
                "h": {
                    "type": "number"
                },
                "o": {
                    "type": "number"
                },
                "p": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "puc-disciplinas API",
	Description:      "API para o projeto Leinadium/puc-disciplinas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
