version: '3'

services:
  data:
    build: ./data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=tcc
        - POSTGRES_PASSWORD=tcc
        - POSTGRES_DB=tcc

  front:
    build: ./front
    ports:
      - "5173:3000"
    environment:
      - PUBLIC_BASE_URL=http://localhost:8080
      - PUBLIC_FRONT_URL=http://localhost:5173

  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - URL_MICRO_LOGIN=http://login:5000
      - URL_MICRO_HISTORICO=http://historico:5001
      - GORM_DSN=host=data user=tcc password=tcc dbname=tcc port=5432 sslmode=disable
      - SECRET_KEY=s902jgfkl2Wfdla9Gan

  login:
    build: ./micro/login
    ports:
      - "5000:5000"

  historico:
    build: ./micro/historico
    ports:
      - "5001:5001"
    environment:
      - POSTGRES_CONN=postgresql+psycopg2://tcc:tcc@data:5432/tcc
  
  sync-cron:
    build: 
      context: ./services/microhorario
      dockerfile: cron.Dockerfile 
    environment:
      - POSTGRES_CONN=postgresql+psycopg2://tcc:tcc@data:5432/tcc

  sync-once:
    build:
      context: ./services/microhorario
      dockerfile: once.Dockerfile
    environment:
      - POSTGRES_CONN=postgresql+psycopg2://tcc:tcc@data:5432/tcc
    restart: "on-failure"


volumes:
  db-data:
